requires 'Getopt::Long';
requires 'Bot::BasicBot', 0.81;
requires 'Calendar::Simple';
requires 'Config::File';
requires 'CGI';
requires 'Date::Simple';
requires 'DBI';
requires 'CGI::Carp';
requires 'Encode::Guess';
requires 'FCGI';
requires 'HTML::Entities';
requires 'HTML::Template', 2.91;
requires 'HTTP::Headers';
requires 'Regexp::Common';
requires 'Text::Table';
requires 'CHI';
requires 'Plack';
requires 'DBD::mysql';
requires 'Lucy';
requires 'JSON';
