#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;
use File::Path qw/mkpath/;

use Ilbot::Config;

my $path = config('search_idx_root');
mkpath $path;
unless (-d $path) {
    die "Storage path '$path' for the search index doesn't exist, and can't reate it\n";
}

_search_backend()->index_all();
